### ISSUE TITLE
Display in the Keyboard and MMIO simulator tool

### ISSUE THREAD

**Issue by mehrabmehdi** [TheThirdOne/rars#39]
So i am trying to print a sting onto the Display in the Keyboard and MMIO simulator tool but it seems to be crashing rars for me every single time right after it the ascii of the first character into the memory and the delay is finised

this is the code im trying to run with the tool:
[riscv1.txt](https://github.com/TheThirdOne/rars/files/3282326/riscv1.txt)

this is the error:

 Exception in thread "RISCV" java.lang.NullPointerException
	at rars.tools.KeyboardAndDisplaySimulator$2.caretUpdate(KeyboardAndDisplaySimulator.java:596)
	at java.desktop/javax.swing.text.JTextComponent.fireCaretUpdate(JTextComponent.java:412)
	at java.desktop/javax.swing.text.JTextComponent$MutableCaretEvent.fire(JTextComponent.java:4489)
	at java.desktop/javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(JTextComponent.java:4511)
	at java.desktop/javax.swing.text.DefaultCaret.fireStateChanged(DefaultCaret.java:812)
	at java.desktop/javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1283)
	at java.desktop/javax.swing.text.DefaultCaret.handleSetDot(DefaultCaret.java:1182)
	at java.desktop/javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1163)
	at java.desktop/javax.swing.text.DefaultCaret$Handler.insertUpdate(DefaultCaret.java:1757)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:757)
	at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716)
	at java.desktop/javax.swing.text.PlainDocument.insertString(PlainDocument.java:131)
	at java.desktop/javax.swing.JTextArea.append(JTextArea.java:468)
	at rars.tools.KeyboardAndDisplaySimulator.displayCharacter(KeyboardAndDisplaySimulator.java:336)
	at rars.tools.KeyboardAndDisplaySimulator.processRISCVUpdate(KeyboardAndDisplaySimulator.java:267)
	at rars.tools.AbstractToolAndApplication.update(AbstractToolAndApplication.java:480)
	at java.base/java.util.Observable.notifyObservers(Observable.java:173)
	at rars.riscv.hardware.Memory$MemoryObservable.notifyObserver(Memory.java:1026)
	at rars.riscv.hardware.Memory.notifyAnyObservers(Memory.java:1056)
	at rars.riscv.hardware.Memory.readProgramStatement(Memory.java:1247)
	at rars.riscv.hardware.Memory.getStatement(Memory.java:808)
	at rars.riscv.hardware.Memory.getStatement(Memory.java:779)
	at rars.simulator.Simulator$SimThread.run(Simulator.java:450)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by mehrabmehdi** [comment]
Seems to work fine with the simulator update before may.

**Comment by zacharyselk** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;There was a bug introduced in 4b2d4b6c418c978af56da96786cf20583f387231 that has caused the display portion of the "Keyboard and Display MMIO Simulator" tool to break.

__Here is the stack trace after using the display tool in that commit:__
~~~~
Exception in thread "RISCV" java.lang.NullPointerException
        at rars.tools.KeyboardAndDisplaySimulator$2.caretUpdate(KeyboardAndDisplaySimulator.java:596)
        at java.desktop/javax.swing.text.JTextComponent.fireCaretUpdate(JTextComponent.java:412)
        at java.desktop/javax.swing.text.JTextComponent$MutableCaretEvent.fire(JTextComponent.java:4489)
        at java.desktop/javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(JTextComponent.java:4511)
        at java.desktop/javax.swing.text.DefaultCaret.fireStateChanged(DefaultCaret.java:812)
        at java.desktop/javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1283)
        at java.desktop/javax.swing.text.DefaultCaret.handleSetDot(DefaultCaret.java:1182)
        at java.desktop/javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1163)
        at java.desktop/javax.swing.text.DefaultCaret$Handler.insertUpdate(DefaultCaret.java:1757)
        at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203)
        at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:757)
        at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716)
        at java.desktop/javax.swing.text.PlainDocument.insertString(PlainDocument.java:131)
        at java.desktop/javax.swing.JTextArea.append(JTextArea.java:468)
        at rars.tools.KeyboardAndDisplaySimulator.displayCharacter(KeyboardAndDisplaySimulator.java:336)
        at rars.tools.KeyboardAndDisplaySimulator.processRISCVUpdate(KeyboardAndDisplaySimulator.java:267)
        at rars.tools.AbstractToolAndApplication.update(AbstractToolAndApplication.java:480)
        at java.base/java.util.Observable.notifyObservers(Observable.java:173)
        at rars.riscv.hardware.Memory$MemoryObservable.notifyObserver(Memory.java:1026)
        at rars.riscv.hardware.Memory.notifyAnyObservers(Memory.java:1056)
        at rars.riscv.hardware.Memory.readProgramStatement(Memory.java:1247)
        at rars.riscv.hardware.Memory.getStatement(Memory.java:808)
        at rars.riscv.hardware.Memory.getStatement(Memory.java:779)
        at rars.simulator.Simulator$SimThread.run(Simulator.java:451)
        at java.base/java.lang.Thread.run(Thread.java:834)
~~~~

__Steps to reproduce:__
* Run rars with java -jar rars.jar
* Load [display_test.txt](https://github.com/TheThirdOne/rars/files/3282676/display_test.txt)
* Assemble the program
* Open the "Keyboard and Display MMIO Simulator" tool
* Set delay length on tool to 1 instruction execution
* Set run speed to 1 inst/sec
* Connect tool to program
* Run the program

__Expected Behaviour:__
&nbsp;&nbsp;&nbsp;&nbsp;To display "Hello World" in the display section on the "Keyboard and Display MMIO Simulator" tool then terminate.

__Observed Behaviour:__
&nbsp;&nbsp;&nbsp;&nbsp;Displays the first character of "Hello World" after performing a ``sw`` instruction to the address 0xFFFF000C (the MMIO for the display) then a thread crashes while attempting to run the instruction immediately following the ``sw`` instruction, resulting in the entire simulator freezing.

**Comment by TheThirdOne** [comment]
Thanks for the report. Pretty sure its fix now, if its still wrong or something else is wrong with the tool don't hesitate to add to this issue.

@zacharyselk, thanks for the extra information. It helped make this a quicker fix.

**Comment by mehrabmehdi** [comment]
Is it possible to apply backspacing to the Display? Currently is reading the ascii code of the backspace as an unknown character and printing it out, would it possible to make it so that it reads the backspace, and moves the cursor back one position and deletes the character there?

**Comment by TheThirdOne** [comment]
AFAIK, the only way of overwriting a character is to move the cursor there and then writing a different character. The relevant documentation for how to move the cursor is:

> When ASCII 7 (bell) is stored in the Transmitter Data register, the cursor in the tool's Display window will be positioned at the (X,Y) coordinate specified by its high-order 3 bytes, following the specified transmission delay. Place the X position (column) in bit positions 20-31 of the Transmitter Data register and place the Y position (row) in bit positions 8-19.  The cursor is not displayed but subsequent transmitted characters will be displayed starting at that position. Position (0,0) is at upper left. Why did I select the ASCII Bell character?  Just for fun!

It would certainly be possible to modify the tool to support backspace changing the cursor, but I would think in most cases the manual cursor positioning would still be the preferred way of moving the cursor.

**Comment by TaylorZowtuk** [comment]
@TheThirdOne I just wanted to let you know that you credited me on the 1.3 release notes with providing detailed information regarding fixing this issue but it was actually @zacharyselk . Just thought id bring that to your attention.

**Comment by TheThirdOne** [comment]
@TaylorZowtuk, thanks for telling me. Its updated now.

I had to rewrite that description after it got deleted once. My attention to detail was probably hindered by my frustration.
